### ISSUE TITLE
Rewamp needed

### ISSUE THREAD

**Issue by MRAXXX** [Copy05/Hconsole#1]
I made extra an account for helping you.
Hconsole needs an rewamp with an better command handler and linux support.

**Comment by ConstantesInt** [comment]
What an coincidence @MRAXXX i was interested in working in Hconsole too. i'm always ready to work on hacking projects.

**Comment by Copy05** [comment]
if you wanna believe or not i'm working already on a Hconsole rewamp. i have to learn how to support Linux with my trashy C code it'll take some time

**Comment by Copy05** [comment]
Sure.

**Comment by Copy05** [comment]
@ConstantesInt @MRAXXX  Done! enjoy
